---
openapi: 3.0.2
info:
  title: quetzal
  description: Quetzalcoatl API (formerly known as CloudTS)
  version: 0.3.0
paths:
  /api/auth/token:
    post:
      summary: Authenticate and obtain a token
      tags:
        - authentication
      operationId: app.api.auth.get_token
      security:
        - basic: []
        - bearer: []
      responses:
        200:
          description: Authentication token
          content:
            application/json:
              schema:
                type: object
  /api/data/workspaces/:
    get:
      summary: Get all workspaces
      tags:
        - data
      operationId: app.api.data.workspace.fetch
      parameters:
      - name: name
        in: query
        description: Filter workspaces by name
        required: false
        schema:
          type: string
      - name: owner
        in: query
        description: Filter workspaces by owner
        required: false
        schema:
          type: string
      - name: deleted
        in: query
        description: Include deleted workspaces
        schema:
          type: boolean
      responses:
        200:
          description: Workspace list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Workspace'
    post:
      summary: Create a new workspace
      tags:
        - data
      operationId: app.api.data.workspace.create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewWorkspace'
        required: true
      responses:
        201:
          description: Workspace created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workspace'
  /api/data/workspaces/{id}:
    parameters:
      - name: id
        in: path
        description: Workspace identifier
        required: true
        schema:
          type: integer
    get:
      summary: Workspace details
      description: Fetchs all details of a workspace
      tags:
        - data
      operationId: app.api.data.workspace.details
      responses:
        200:
          description: Workspace details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workspace'
    delete:
      summary: Request deletion of a workspace
      description: |-
        Marks a workspace for deletion.
        Workspaces cannot be immediately deleted, due to complex resource management.
        The status of the workspace can be requested on this same path, using a GET
        instead of a DELETE.
      tags:
        - data
      operationId: app.api.data.workspace.delete
      responses:
        202:
          description: Workspace marked for deletion
  /api/data/workspaces/{id}/commit:
    put:
      summary: Commit a workspace
      description: |-
        Requests a workspace commit. That is, all metadata added or modified
        in this workspace will be committed to the global workspace, becoming
        available to all users. Metadata versions will be incremented.
      tags:
        - data
      operationId: app.api.data.workspace.commit
      parameters:
        - name: id
          in: path
          description: Workspace identifier
          required: true
          schema:
            type: integer
      responses:
        202:
          description: Successfully requested a workspace commit operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workspace'
  /api/data/workspaces/{id}/scan:
    put:
      summary: Update workspace views
      description: |-
        Requests the update of the views of a workspace. All the internal databases
        used for the query operation will be updated to contain the latest modifications
        of the metadata.
      tags:
        - data
      operationId: app.api.data.workspace.scan
      parameters:
        - name: id
          in: path
          description: Workspace identifier
          required: true
          schema:
            type: integer
      responses:
        202:
          description: Successfully requested a workspace scan operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workspace'
  /api/data/workspaces/{id}/files/:
    parameters:
      - name: id
        in: path
        description: Workspace identifier
        required: true
        schema:
          type: integer
    get:
      summary: List workspace files
      description: |-
        Fetchs all the files that have been added in this workspace. Files
        whose metadata has been modified in this workspace will also be
        included.
      tags:
        - data
      operationId: app.api.data.workspace.files
      responses:
        200:
          description: List of workspace files
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
    post:
      summary: Add a new file
      description: |-
        Upload a new file by sending its contents. The file will not have any
        additional metadata associated to it.
      tags:
        - data
      operationId: app.api.data.workspace.add_file
      requestBody:
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        201:
          description: File uploaded successfully
          content:
            application/json:
              schema:
                type: object
  /api/data/workspaces/{id}/files/{uuid}:
    parameters:
      - name: id
        in: path
        description: Workspace identifier
        required: true
        schema:
          type: integer
      - name: uuid
        in: path
        description: File identifier
        required: true
        schema:
          type: string
          format: uuid
    get:
      summary: Fetch file metadata or contents
      description: |-
        Serves the file contents or its metadata, according to the accepted
        content response header. When the metadata is requested, this returns
        the updated version with the modifications that may have been
        introduced in this workspace.
      tags:
        - data
      operationId: app.api.data.workspace.fetch_workspace_file
      responses:
        200:
          description: File contents or metadata
          content:
            application/json:
              schema:
                type: object
            application/octet-stream:
              schema:
                type: string
                format: binary
    patch:
      summary: Modify file metadata
      description: |-
        Change the file metadata ...
      tags:
        - data
      operationId: app.api.data.workspace.update_metadata
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        200:
          description: Metadata successfully updated
          content:
            application/json:
              schema:
                type: object
  /api/data/files/{uuid}:
    parameters:
      - name: uuid
        in: path
        description: File identifier
        required: true
        schema:
          type: string
          format: uuid
    get:
      summary: Fetch file metadata or contents
      description: |-
        Serves the file contents or its metadata, according to the accepted
        content response header. In the case of metadata, this endpoint returns
        the most recent metadata that has been committed.
      tags:
        - data
      operationId: app.api.data.workspace.fetch_file
      responses:
        200:
          description: File contents or metadata
          content:
            application/json:
              schema:
                type: object
            application/octet-stream:
              schema:
                type: string
                format: binary
components:
  schemas:
    NewWorkspace:
      title: Workspace creation input type
      description: Input data type to create a workspace
      required:
      - families
      - name
      - description
      type: object
      properties:
        name:
          type: string
        families:
          description: |-
            Metadata requested for this workspace. The metadata request
            is represented by an object (i.e. a dictionary). The object keys are
            metadata family names; their values are the version number of the family.
            When the version is null, it is equivalent to requesting the latest
            version available.
          type: object
        description:
          description: Descriptive text of the purpose of this workspace
          type: string
        temporary:
          type: boolean
      example: |-
        {
            "name": "my_workspace",
            "families": {
                "base": null,
                "application": 123
            },
            "temporary": false
        }
    Workspace:
      title: Workspace details type
      description: Workspace details
      type: object
      properties:
        id:
          description: Workspace ID
          type: integer
        status:
          description: Workspace status
          enum:
          - initializing
          - ready
          - processing
          - invalid
          - conflict
          - deleted
        description:
          description: Descriptive text of the purpose of this workspace
          type: string
        families:
          description: |-
            Families and corresponding versions used in this workspace.
            This property is a object whose keys are family names and values are
            integers.
          type: object
        creation_date:
          format: date-time
          description: Date when the workspace was created
          type: string
        temporary:
          description: |-
            Whether this workspace is temporary or not. Temporary workspaces
            are automatically deleted after some time.
          type: boolean
        owner:
          description: User who owns this workpace
          type: string
        data_url:
          description: URL of a remote storage location for files used in this workspace
          type: string
          nullable: true
        name:
          description: Name of the workspace
          type: string
      example: |-
        {
            "id": 1,
            "status": "ready",
            "description": "Details on what this workspace is for",
            "families": {},
            "creation_date": "2019-28-02T12:23:55",
            "temporary": false,
            "owner": "username",
            "data_url": "gs://some_bucket_name"
        }
  securitySchemes:
    basic:
      type: http
      scheme: basic
      x-basicInfoFunc: app.api.auth.check_basic
    bearer:
      type: http
      scheme: bearer
      x-bearerInfoFunc: app.api.auth.check_bearer
security:
  - bearer: []
tags:
  - name: authentication
    description: Authentication operations
  - name: data
    description: Data operations
