apiVersion: v1
kind: Secret
metadata:
  name: {{ include "quetzal.fullname" . }}-app-secrets
  labels:
    app.kubernetes.io/component: app
{{ include "quetzal.labels" . | indent 4 }}
type: Opaque
stringData:
  secret_key: {{ required "A valid .Values.app.secret_key is required!" .Values.app.secret_key | quote }}
