apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "quetzal.fullname" . }}-app-hpa
  labels:
    app.kubernetes.io/component: app
{{ include "quetzal.labels" . | indent 4}}
spec:
    minReplicas: 1
    maxReplicas: 10
    scaleTargetRef:
      apiVersion: extensions/v1beta1
      kind: Deployment
      name: {{ include "quetzal.fullname" . }}-app
