apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app.kubernetes.io/component: app
{{ include "quetzal.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: flask
      port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "quetzal.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: app
