apiVersion: v1
kind: Secret
metadata:
  name: {{ include "quetzal.fullname" . }}-app-secrets
  labels:
    app.kubernetes.io/component: app
{{ include "quetzal.labels" . | indent 4 }}
type: Opaque
stringData:
  flask_secret_key: {{ required "A valid .Values.app.flaskSecretKey is required!" .Values.app.flaskSecretKey | quote }}
