apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "quetzal.fullname" . }}-db
  labels:
    app.kubernetes.io/component: database
{{ include "quetzal.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "quetzal.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: database
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "quetzal.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: database
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
          imagePullPolicy: {{ .Values.db.image.pullPolicy }}
          command:  
            - docker-entrypoint.sh
            - postgres
            - -c
            - config_file=/etc/postgresql/postgresql.conf
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          resources:
            {{- toYaml .Values.db.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /srv/data
              name: db-data-volume
          env:
            # for the database contents, as documented in the postgres:latest
            # Dockerfile configuration in hub.docker.com, it is recommended to
            # change the PGDATA to a subdirectory. I tried not using a
            # subdirectory before (/var/lib/postgresql/data or
            # /var/lib/postgresql/data/pgdata). The first case doesn't work
            # because there is a volume in the Dockerfile which creates a silent
            # conflict and then the persistent data is lost. The second case
            # doesn't work because postgres complains that this is a mount
            # point.
            - name: PGDATA
              value: /srv/data/pgdata
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "quetzal.fullname" . }}-db-secrets
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "quetzal.fullname" . }}-db-secrets
                  key: password
      restartPolicy: Always
      volumes:
        - name: db-data-volume
          persistentVolumeClaim:
            claimName: {{ template "quetzal.fullname" . }}-db-pvc
      {{- with .Values.db.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.db.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.db.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
