apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "quetzal.fullname" . }}-db-pvc
  labels:
    app.kubernetes.io/component: database
{{ include "quetzal.labels" . | indent 4}}
spec:
  storageClassName: {{ include "quetzal.fullname" . }}-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
