apiVersion: v1
kind: Secret
metadata:
  name: {{ include "quetzal.fullname" . }}-db-secrets
  labels:
    app.kubernetes.io/component: database
{{ include "quetzal.labels" . | indent 4 }}
type: Opaque
stringData:
  username: {{ required "A valid .Values.db.username is required!" .Values.db.username | quote }}
  password: {{ required "A valid .Values.db.password is required!" .Values.db.password | quote }}
