apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app.kubernetes.io/component: database
{{ include "quetzal.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "quetzal.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: database
