apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "quetzal.fullname" . }}-rabbitmq
  labels:
    app.kubernetes.io/component: rabbitmq
{{ include "quetzal.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "quetzal.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: rabbitmq
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "quetzal.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: rabbitmq
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.rabbitmq.image.repository }}:{{ .Values.rabbitmq.image.tag }}"
          imagePullPolicy: {{ .Values.rabbitmq.image.pullPolicy }}
          ports:
            - name: rabbitmq
              containerPort: 5672
              protocol: TCP
            - name: rabbitmq-mgmt
              containerPort: 15672
              protocol: TCP
          resources:
            {{- toYaml .Values.rabbitmq.resources | nindent 12 }}
      restartPolicy: Always
      {{- with .Values.db.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.db.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.db.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
