apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app.kubernetes.io/component: rabbitmq
{{ include "quetzal.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: rabbitmq
      port: 5672
      targetPort: 5672
      protocol: TCP
    - name: rabbitmq-management
      port: 15672
      targetPort: 15672
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "quetzal.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: rabbitmq
