# Documentation of these yaml, their schema and what everything means is
# available on https://kubernetes.io/docs/reference/
apiVersion: v1
kind: Service
metadata:
  # Unique key for the service instance
  name: db
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector:
    name: db
    app: quetzal
