# Documentation of these yaml, their schema and what everything means is
# available on https://kubernetes.io/docs/reference/
apiVersion: v1
kind: Service
metadata:
  # Unique key for the service instance
  name: nginx
spec:
  type: LoadBalancer
  loadBalancerIP: 35.240.62.176
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
  selector:
    name: nginx
    app: quetzal
