# Documentation of these yaml, their schema and what everything means is
# available on https://kubernetes.io/docs/reference/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    name: rabbitmq
    app: quetzal
spec:
  replicas: 1
  selector:
    matchLabels:
      name: rabbitmq
      app: quetzal
  template:
    metadata:
      labels:
        name: rabbitmq
        app: quetzal
    spec:
      containers:
        - name: rabbitmq
          image: gcr.io/quetzal/quetzal/rabbitmq:0.2.0
          imagePullPolicy: Always
          ports:
            - containerPort:  5672
            - containerPort: 15672
          resources:
            requests:
              # Memory request set to the value documented in
              # https://www.rabbitmq.com/production-checklist.html#resource-limits-ram
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "1000m"
      restartPolicy: Always
