# Documentation of these yaml, their schema and what everything means is
# available on https://kubernetes.io/docs/reference/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  labels:
    name: rabbitmq-pods
spec:
  replicas: 1
  selector:
    matchLabels:
      name: rabbitmq-pods
  template:
    metadata:
      labels:
        name: rabbitmq-pods
    spec:
      containers:
        - name: rabbitmq
          image: gcr.io/dojeda-sandbox/quetzal/rabbitmq:0.1.0
          imagePullPolicy: Always
          ports:
            - containerPort:  5672
            - containerPort: 15672
          resources: {}
      restartPolicy: Always
