# Documentation of these yaml, their schema and what everything means is
# available on https://kubernetes.io/docs/reference/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    name: web
    app: quetzal
spec:
  replicas: 1
  selector:
    matchLabels:
      name: web
      app: quetzal
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: web
        app: quetzal
    spec:
      containers:
        - name: web
          image: gcr.io/quetzal-omind/quetzal/app:0.1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          resources: {}
          volumeMounts:
            - mountPath: /code/conf
              name: app-secret-files-volume
          env:
            - name: SERVER_NAME
              value: stage.quetz.al
            - name: FLASK_ENV
              value: staging
            - name: QUETZAL_BACKGROUND_JOBS
              value: "1"
            - name: USE_GUNICORN
              value: "1"
            - name: QUETZAL_ADMIN_MAIL
              value: quetzal.api@gmail.com
            - name: QUETZAL_GCP_DATA_BUCKET
              value: gs://quetzal-stage-data
            - name: QUETZAL_GCP_BACKUP_BUCKET
              value: gs://quetzal-stage-backups
            - name: DB_HOST
              value: db
            - name: DB_PORT
              value: "5432"
            - name: DB_DATABASE
              value: quetzal
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: stage-app-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: stage-app-secrets
                  key: DB_PASSWORD
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_PORT
              value: "5672"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: stage-app-secrets
                  key: SECRET_KEY
      restartPolicy: Always
      volumes:
        - name: app-secret-files-volume
          secret:
            secretName: stage-app-secrets
