apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: web
  labels:
    name: web
    app: quetzal
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: web
  targetCPUUtilizationPercentage: 50
