# Documentation of these yaml, their schema and what everything means is
# available on https://kubernetes.io/docs/reference/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    name: worker
    app: quetzal
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker
      app: quetzal
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: worker
        app: quetzal
    spec:
      containers:
        - name: worker
          image: gcr.io/quetzal/quetzal/app:0.1.0
          imagePullPolicy: Always
          command:
            - /entrypoint-worker.sh
          resources: {}
          volumeMounts:
            - mountPath: /code/conf
              name: app-secret-files-volume
          env:
            - name: SERVER_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: server_name
            - name: FLASK_ENV
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: flask_env
            - name: QUETZAL_ADMIN_MAIL
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: admin_mail
            - name: QUETZAL_GCP_DATA_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: data_bucket
            - name: QUETZAL_GCP_BACKUP_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: backup_bucket
            - name: DB_HOST
              value: db
            - name: DB_PORT
              value: "5432"
            - name: DB_DATABASE
              value: quetzal
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: stage-app-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: stage-app-secrets
                  key: DB_PASSWORD
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: stage-app-secrets
                  key: SECRET_KEY
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_PORT
              value: "5672"
      restartPolicy: Always
      volumes:
        - name: app-secret-files-volume
          secret:
            secretName: stage-app-secrets
