apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: worker
  labels:
    name: worker
    app: quetzal
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: worker
  targetCPUUtilizationPercentage: 50
