apiVersion: v1
name: quetzal
version: 0.0.7         # Chart version
appVersion: 0.4.0-dev  # Quetzal app version
description: A RESTful API designed to store data files and manage their associated metadata.
home: https://quetz.al
maintainers:
  - name: David Ojeda
    email: quetzal.api@gmail.com
