## Default values for quetzal.
## This is a YAML-formatted file.
## Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

# General configuration
general:
  adminMail: david@omind.me
  serverName: quetzal.omind.me
  credentialsSecret: production-credentials-secrets
  dataBucket: gs://quetzal-prod-data
  backupBucket: gs://quetzal-prod-backups

ingress:
  tlsSecret: production-tls-secret

# Retained disk configuration (for database disk)
storage:
  type: pd-standard
  provisioner: kubernetes.io/gce-pd
  volumeBindingMode: Immediate

app:
  # general pod configuration
  image:
    repository: eu.gcr.io/quetzal-omind/quetzal/app
    tag: 0.5.0
    pullPolicy: IfNotPresent
  resources:
    limits:
      memory: 4Gi
      cpu: 1000m
    requests:
      memory: 256Mi
      cpu: 100m
  nodeSelector: {}
  tolerations: []
  affinity: {}

  # app/worker specific configuration
  flask_env: production

  # Other configuration entries that should not be set here. They should be
  # set using --set key=value when doing helm install:
  # flask_secret_key: ...

worker:
  resources:
    limits:
      memory: 4Gi
      cpu: 1000m
    requests:
      memory: 256Mi
      cpu: 100m
  nodeSelector: {}
  tolerations: []
  affinity: {}

db:
  image:
    repository: eu.gcr.io/quetzal-omind/quetzal/db
    tag: 0.5.0
    pullPolicy: IfNotPresent
  resources:
    limits:
      memory: 1Gi
      cpu: 1000m
    requests:
      memory: 64Mi
      cpu: 100m
  nodeSelector: {}
  tolerations: []
  affinity: {}

  # Other configuration entries that should not be set here. They should be
  # set using --set key=value when doing helm install:
  # username: ...
  # password: ...

rabbitmq:
  image:
    repository: eu.gcr.io/quetzal-omind/quetzal/rabbitmq
    tag: 0.5.0
    pullPolicy: IfNotPresent
  resources:
    limits:
      memory: 256Mi
      cpu: 250m
    requests:
      memory: 128Mi
      cpu: 250m
  nodeSelector: {}
  tolerations: []
  affinity: {}
